using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Unity.Collections;

namespace AncientMonkey
{
    public static class Settings
    {
        public static Dictionary<string, object> settingsValue = new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase)
        {
            {"SandboxMode", false},
            {"Cheats", false},
            {"NewWeaponStartingCost", 325f},
            {"IncrementalNewWeaponStartingCost", 159f},
            {"IncrementalNewWeaponCostMultiplier", 1.04f},
            {"StrongerWeaponStartingCost", 250f},
            {"IncrementalStrongerWeaponStartingCost", 300f},
            {"IncrementalStrongerWeaponCostMultiplier", 1.04f},
            {"NewAbilityStartingCost", 5000f},
            {"IncrementalNewAbilityStartingCost", 1000f},
            {"IncrementalNewAbilityCostMultiplier", 1f},
            {"ExtraLuckStartingCost", 700f},
            {"ExtraLuckCostIncreaseMultiplier", 1.35f},
            {"ExtraLuckUpgradeCount", 20},
            {"ExtraAbilitySlotStartingCost", 100000f},
            {"ExtraAbilitySlotIncreaseMultiplier", 1.15f},
            {"ExtraAbilitySlotUpgradeCount", 1},
            {"ExtraWeaponSlotStartingCost", 50000f},
            {"ExtraWeaponSlotIncreaseMultiplier", 1.15f},
            {"ExtraWeaponSlotUpgradeCount", 1},
            {"ExtraStrongerSlotStartingCost", 75000f},
            {"ExtraStrongerSlotIncreaseMultiplier", 1.15f},
            {"ExtraStrongerSlotUpgradeCount", 1},
            {"NewWeaponStartingSlot", 3},
            {"NewAbilityStartingSlot", 1},
            {"StrongerWeaponStartingSlot", 3},

            {"Upgrade1Enabled", true},
            {"Upgrade1Cost", 125000f},
            {"NewWeaponStartingCost1", 450f},
            {"IncrementalNewWeaponStartingCost1", 350f},
            {"IncrementalNewWeaponCostMultiplier1", 1.06f},
            {"StrongerWeaponStartingCost1", 950f},
            {"IncrementalStrongerWeaponStartingCost1", 750f},
            {"IncrementalStrongerWeaponCostMultiplier1", 1.06f},
            {"NewAbilityStartingCost1", 6000f},
            {"IncrementalNewAbilityStartingCost1", 750f},
            {"IncrementalNewAbilityCostMultiplier1", 1f},
            {"NewWeaponSlotBonus1", 1},
            {"StrongerWeaponSlotBonus1", 1},
            {"NewAbilitySlotBonus1", 1},

            {"Upgrade2Enabled", true},
            {"Upgrade2Cost", 1000000f},
            {"NewWeaponStartingCost2", 2350f},
            {"IncrementalNewWeaponStartingCost2", 1750f},
            {"IncrementalNewWeaponCostMultiplier2", 1.06f},
            {"StrongerWeaponStartingCost2", 3500f},
            {"IncrementalStrongerWeaponStartingCost2", 2250f},
            {"IncrementalStrongerWeaponCostMultiplier2", 1.06f},
            {"NewAbilityStartingCost2", 5500f},
            {"IncrementalNewAbilityStartingCost2", 500f},
            {"IncrementalNewAbilityCostMultiplier2", 1f},
            {"NewWeaponSlotBonus2", 1},
            {"StrongerWeaponSlotBonus2", 1},
            {"NewAbilitySlotBonus2", 1},
            {"XpEnabled", true},
            {"StartingMaxXp", 2},
            {"MaxXpIncrease", 2},

            {"BaseRareChance", 7f},
            {"BaseEpicChance", 0f},
            {"BaseLegendaryChance", 0f},
            {"BaseExoticChance", 0f},
            {"BaseRareChanceUntilEpicChance", 14f},
            {"BaseEpicChanceUntilLegendaryChance", 12f},
            {"BaseLegendaryChanceUntilExoticChance", 9f},
            {"BaseRareChanceDecrease", 5f},
            {"BaseEpicChanceDecrease", 1.45f},
            {"BaseLegendaryChanceDecrease", 0.85f},
            {"BaseExoticChanceDecrease", 0.50f},

            {"StrongBaseRareChance", 10f},
            {"StrongBaseEpicChance", 0f},
            {"StrongBaseLegendaryChance", 0f},
            {"StrongBaseExoticChance", 0f},
            {"StrongBaseRareChanceUntilEpicChance", 0},
            {"StrongBaseEpicChanceUntilLegendaryChance", 12},
            {"StrongBaseLegendaryChanceUntilExoticChance", 9},
            {"StrongBaseRareChanceDecrease", 6.7f},
            {"StrongBaseEpicChanceDecrease", 2f},
            {"StrongBaseLegendaryChanceDecrease", 1.15f},
            {"StrongBaseExoticChanceDecrease", 0.75f},

            {"Upgrade1EpicChance", 25f},
            {"Upgrade1LegendaryChance", 2f},
            {"Upgrade1ExoticChance", 0f},
            {"Upgrade1GodlyChance", 0f},
            {"Upgrade1EpicChanceUntilLegendaryChance", 12f},
            {"Upgrade1LegendaryChanceUntilExoticChance", 9f},
            {"Upgrade1ExoticChanceUntilGodlyChance", 9f},
            {"Upgrade1EpicChanceDecrease", 1.45f},
            {"Upgrade1LegendaryChanceDecrease", 0.85f},
            {"Upgrade1ExoticChanceDecrease", 0.50f},
            {"Upgrade1GodlyChanceDecrease", 0.30f},


            {"StrongUpgrade1EpicChance", 30f},
            {"StrongUpgrade1LegendaryChance", 5f},
            {"StrongUpgrade1ExoticChance", 0f},
            {"StrongUpgrade1GodlyChance", 0f},
            {"StrongUpgrade1EpicChanceUntilLegendaryChance", 12f},
            {"StrongUpgrade1LegendaryChanceUntilExoticChance", 9f},
            {"StrongUpgrade1ExoticChanceUntilGodlyChance", 7f},
            {"StrongUpgrade1EpicChanceDecrease", 2f},
            {"StrongUpgrade1LegendaryChanceDecrease", 1.15f},
            {"StrongUpgrade1ExoticChanceDecrease", 0.75f},
            {"StrongUpgrade1GodlyChanceDecrease", 0.55f},

            {"Upgrade2LegendaryChance", 2f},
            {"Upgrade2ExoticChance", 0f},
            {"Upgrade2GodlyChance", 0f},
            {"Upgrade2OmegaChance", 0f},
            {"Upgrade2LegendaryChanceUntilExoticChance", 9f},
            {"Upgrade2ExoticChanceUntilGodlyChance", 9f},
            {"Upgrade2GodlyChanceUntilOmegaChance", 9f},
            {"Upgrade2LegendaryChanceDecrease", 0.85f},
            {"Upgrade2ExoticChanceDecrease", 0.50f},
            {"Upgrade2GodlyChanceDecrease", 0.30f},
            {"Upgrade2OmegaChanceDecrease", 0.15f},

            {"StrongUpgrade2LegendaryChance", 25f},
            {"StrongUpgrade2ExoticChance", 2f},
            {"StrongUpgrade2GodlyChance", 0f},
            {"StrongUpgrade2OmegaChance", 0f},
            {"StrongUpgrade2LegendaryChanceUntilExoticChance", 9f},
            {"StrongUpgrade2ExoticChanceUntilGodlyChance", 7f},
            {"StrongUpgrade2GodlyChanceUntilOmegaChance", 6f},
            {"StrongUpgrade2LegendaryChanceDecrease", 1.15f},
            {"StrongUpgrade2ExoticChanceDecrease", 0.75f},
            {"StrongUpgrade2GodlyChanceDecrease", 0.55f},
            {"StrongUpgrade2OmegaChanceDecrease", 0.3f},
        };
        public static Dictionary<string, object> baseValue = new Dictionary<string, object>()
        {
               {"SandboxMode", false},
            {"Cheats", false},
            {"NewWeaponStartingCost", 325f},
            {"IncrementalNewWeaponStartingCost", 159f},
            {"IncrementalNewWeaponCostMultiplier", 1.04f},
            {"StrongerWeaponStartingCost", 250f},
            {"IncrementalStrongerWeaponStartingCost", 300f},
            {"IncrementalStrongerWeaponCostMultiplier", 1.04f},
            {"NewAbilityStartingCost", 5000f},
            {"IncrementalNewAbilityStartingCost", 1000f},
            {"IncrementalNewAbilityCostMultiplier", 1f},
            {"ExtraLuckStartingCost", 700f},
            {"ExtraLuckCostIncreaseMultiplier", 1.35f},
            {"ExtraLuckUpgradeCount", 20},
            {"ExtraAbilitySlotStartingCost", 100000f},
            {"ExtraAbilitySlotIncreaseMultiplier", 1.15f},
            {"ExtraAbilitySlotUpgradeCount", 1},
            {"ExtraWeaponSlotStartingCost", 50000f},
            {"ExtraWeaponSlotIncreaseMultiplier", 1.15f},
            {"ExtraWeaponSlotUpgradeCount", 1},
            {"ExtraStrongerSlotStartingCost", 75000f},
            {"ExtraStrongerSlotIncreaseMultiplier", 1.15f},
            {"ExtraStrongerSlotUpgradeCount", 1},
            {"NewWeaponStartingSlot", 3},
            {"NewAbilityStartingSlot", 1},
            {"StrongerWeaponStartingSlot", 3},

            {"Upgrade1Enabled", true},
            {"Upgrade1Cost", 125000f},
            {"NewWeaponStartingCost1", 450f},
            {"IncrementalNewWeaponStartingCost1", 350f},
            {"IncrementalNewWeaponCostMultiplier1", 1.06f},
            {"StrongerWeaponStartingCost1", 950f},
            {"IncrementalStrongerWeaponStartingCost1", 750f},
            {"IncrementalStrongerWeaponCostMultiplier1", 1.06f},
            {"NewAbilityStartingCost1", 6000f},
            {"IncrementalNewAbilityStartingCost1", 750f},
            {"IncrementalNewAbilityCostMultiplier1", 1f},
            {"NewWeaponSlotBonus1", 1},
            {"StrongerWeaponSlotBonus1", 1},
            {"NewAbilitySlotBonus1", 1},

            {"Upgrade2Enabled", true},
            {"Upgrade2Cost", 1000000f},
            {"NewWeaponStartingCost2", 2350f},
            {"IncrementalNewWeaponStartingCost2", 1750f},
            {"IncrementalNewWeaponCostMultiplier2", 1.06f},
            {"StrongerWeaponStartingCost2", 3500f},
            {"IncrementalStrongerWeaponStartingCost2", 2250f},
            {"IncrementalStrongerWeaponCostMultiplier2", 1.06f},
            {"NewAbilityStartingCost2", 5500f},
            {"IncrementalNewAbilityStartingCost2", 500f},
            {"IncrementalNewAbilityCostMultiplier2", 1f},
            {"NewWeaponSlotBonus2", 1},
            {"StrongerWeaponSlotBonus2", 1},
            {"NewAbilitySlotBonus2", 1},
            {"XpEnabled", true},
            {"StartingMaxXp", 2},
            {"MaxXpIncrease", 2},

            {"BaseRareChance", 7f},
            {"BaseEpicChance", 0f},
            {"BaseLegendaryChance", 0f},
            {"BaseExoticChance", 0f},
            {"BaseRareChanceUntilEpicChance", 14f},
            {"BaseEpicChanceUntilLegendaryChance", 12f},
            {"BaseLegendaryChanceUntilExoticChance", 9f},
            {"BaseRareChanceDecrease", 5f},
            {"BaseEpicChanceDecrease", 1.45f},
            {"BaseLegendaryChanceDecrease", 0.85f},
            {"BaseExoticChanceDecrease", 0.50f},

            {"StrongBaseRareChance", 10f},
            {"StrongBaseEpicChance", 0f},
            {"StrongBaseLegendaryChance", 0f},
            {"StrongBaseExoticChance", 0f},
            {"StrongBaseRareChanceUntilEpicChance", 0},
            {"StrongBaseEpicChanceUntilLegendaryChance", 12},
            {"StrongBaseLegendaryChanceUntilExoticChance", 9},
            {"StrongBaseRareChanceDecrease", 6.7f},
            {"StrongBaseEpicChanceDecrease", 2f},
            {"StrongBaseLegendaryChanceDecrease", 1.15f},
            {"StrongBaseExoticChanceDecrease", 0.75f},

            {"Upgrade1EpicChance", 25f},
            {"Upgrade1LegendaryChance", 2f},
            {"Upgrade1ExoticChance", 0f},
            {"Upgrade1GodlyChance", 0f},
            {"Upgrade1EpicChanceUntilLegendaryChance", 12f},
            {"Upgrade1LegendaryChanceUntilExoticChance", 9f},
            {"Upgrade1ExoticChanceUntilGodlyChance", 9f},
            {"Upgrade1EpicChanceDecrease", 1.45f},
            {"Upgrade1LegendaryChanceDecrease", 0.85f},
            {"Upgrade1ExoticChanceDecrease", 0.50f},
            {"Upgrade1GodlyChanceDecrease", 0.30f},


            {"StrongUpgrade1EpicChance", 30f},
            {"StrongUpgrade1LegendaryChance", 5f},
            {"StrongUpgrade1ExoticChance", 0f},
            {"StrongUpgrade1GodlyChance", 0f},
            {"StrongUpgrade1EpicChanceUntilLegendaryChance", 12f},
            {"StrongUpgrade1LegendaryChanceUntilExoticChance", 9f},
            {"StrongUpgrade1ExoticChanceUntilGodlyChance", 7f},
            {"StrongUpgrade1EpicChanceDecrease", 2f},
            {"StrongUpgrade1LegendaryChanceDecrease", 1.15f},
            {"StrongUpgrade1ExoticChanceDecrease", 0.75f},
            {"StrongUpgrade1GodlyChanceDecrease", 0.55f},

            {"Upgrade2LegendaryChance", 2f},
            {"Upgrade2ExoticChance", 0f},
            {"Upgrade2GodlyChance", 0f},
            {"Upgrade2OmegaChance", 0f},
            {"Upgrade2LegendaryChanceUntilExoticChance", 9f},
            {"Upgrade2ExoticChanceUntilGodlyChance", 9f},
            {"Upgrade2GodlyChanceUntilOmegaChance", 9f},
            {"Upgrade2LegendaryChanceDecrease", 0.85f},
            {"Upgrade2ExoticChanceDecrease", 0.50f},
            {"Upgrade2GodlyChanceDecrease", 0.30f},
            {"Upgrade2OmegaChanceDecrease", 0.15f},

            {"StrongUpgrade2LegendaryChance", 25f},
            {"StrongUpgrade2ExoticChance", 2f},
            {"StrongUpgrade2GodlyChance", 0f},
            {"StrongUpgrade2OmegaChance", 0f},
            {"StrongUpgrade2LegendaryChanceUntilExoticChance", 9f},
            {"StrongUpgrade2ExoticChanceUntilGodlyChance", 7f},
            {"StrongUpgrade2GodlyChanceUntilOmegaChance", 6f},
            {"StrongUpgrade2LegendaryChanceDecrease", 1.15f},
            {"StrongUpgrade2ExoticChanceDecrease", 0.75f},
            {"StrongUpgrade2GodlyChanceDecrease", 0.55f},
            {"StrongUpgrade2OmegaChanceDecrease", 0.3f},
        };
    }
    
}
